#esse arquivo vai sobreescrever o application.yml somente nos campos que foram definidos neste arquivo!
spring:
  application:
    name: libraryapi-production
  jpa:
    show-sql: false
logging:
  level:
    io:
      github:
        feeato:
          libraryapi:
            controller: trace
            LibraryapiApplication: info
